kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  # Build
  - name: build-docker-api
    image: plugins/docker
    settings:
      dockerfile: ./Sources/src/main/docker/Dockerfile-custom.native-micro
      context: ./Sources/
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/valentin.clergue/mongeat
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD

  # Database
  - name: deploy-container-mongodb
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: mongo
      CONTAINERNAME: mongeat-mongodb
      COMMAND: create
      OVERWRITE: true
      PRIVATE: true
      ADMINS: valentinclergue,mathisribemont
    when:
      branch:
        - master
    #depends_on: [ build-docker-api ]

  # Api
  - name: deploy-api-container
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/valentin.clergue/mongeat
      CONTAINERNAME: mongeat-api
      COMMAND: create
      OVERWRITE: true
      ADMINS: valentinclergue,mathisribemont
    when:
      branch:
        - master
    depends_on: [ build-docker-api]